.TH PS 1 "Весна 2019" "СПО, лабораторная работа №2"

.SH НАЗВАНИЕ
ps \- отображает состояние процессов на момент выполнения команды

.SH СИНТАКСИС
.B ps
[\fIопции\fP]

.SH ОПИСАНИЕ
.B ps
выводит информацию о выполняющихся процессах. При отсутствии параметров выбираются
процессы c действующем идентификатором пользователя и терминалом, с которыми
вызван \fBps\fP, то есть \fBeffective uid = $EUID, tty = $TTY\fP. Вывод
состоит из ID процесса, идентификатора терминала, времени исполнения и названия команды.

.SH ПАРАМЕТРЫ

.SS ВЫБОРКА ПРОЦЕССОВ

.TP
.B -a
Отобразить процессы всех пользователей, привязанные к контролирующему терминалу.

.TP
.B -A
Отобразить все активные процессы.

.TP
.B -x
Отобразить процессы, не привязанные к контролирующему терминалу
(демоны, работающие в фоновом режиме).

.SS ИЗМЕНЕНИЕ ВЫВОДА

См. раздел
.B ВЫВОД
для более подробной информации.

.TP
.B -f
Включить в вывод полную (\fIfull\fP) информацию.

.TP
.B -l
Включить в вывод подробную (\fIlong\fP) информацию.

.SH ВЫВОД

Следующие столбцы включены в вывод \fBps\fP в зависимости от выбранных параметров
форматирования:

.TP
.B F
(Только в режиме \fIlong\fP) Флаги процесса, зависящие от конкретной платформы.

.TP
.B S
(Только в режиме \fIlong\fP) Состояние процесса, зависящее от конкретной платформы.
Может указывать, выполняется ли процесс в данное время, ожидает события или находится в очереди.

.TP
.B UID
(В режимах \fIlong\fP, \fIfull\fP) Числовой идентификатор (имя пользователя в режиме \fIfull\fP)
владельца процесса.

.TP
.B PID
Числовой идентификатор процесса, может использоваться для его завершения — см.
.BR kill (1)

.TP
.B PPID
(В режимах \fIlong\fP, \fIfull\fP) Числовой идентификатор процесса-родителя.

.TP
.B C
(В режимах \fIlong\fP, \fIfull\fP) Показатель утилизации процессора, используется планировщиком.

.TP
.B PRI
(Только в режиме \fIlong\fP) Приоритет процесса. Большие значения соответствуют низкому приоритету.

.TP
.B NI
(Только в режиме \fIlong\fP) Значение для вычисления приоритета.

.TP
.B ADDR
(Только в режиме \fIlong\fP) Адрес процесса в памяти.

.TP
.B SZ
(Только в режиме \fIlong\fP) Размер процесса в памяти.

.TP
.B WCHAN
(Только в режиме \fIlong\fP) Событие, которого ожидает процесс, если находится в режиме ожидания.

.TP
.B STIME
(Только в режиме \fIfull\fP) Время запуска процесса.

.TP
.B TTY
Контролирующий терминал процесса.

.TP
.B TIME
Суммарное процессорное время, затраченное на исполнение процесса.

.TP
.B CMD
Исполняемая команда (включая аргументы в режиме \fIfull\fP).
