.TH PS 1 "Весна 2019" "СПО, лабораторная работа №2"

.SH НАЗВАНИЕ
ps \- отображает состояние процессов на момент выполнения команды

.SH СИНТАКСИС
.B ps
[\fIопции\fP]

.SH ОПИСАНИЕ
.B ps
выводит информацию о выполняющихся процессах. При отсутствии параметров выбираются
процессы c действующем идентификатором пользователя и терминалом, с которыми
вызван \fBps\fP, то есть \fBeffective uid = $EUID, tty = $TTY\fP. Вывод
состоит из ID процесса, идентификатора терминала, времени исполнения и названия команды.

.SH ПАРАМЕТРЫ

.SS ВЫБОРКА ПРОЦЕССОВ

.TP
.B -a
Отобразить процессы всех пользователей, привязанные к контролирующему терминалу.

.TP
.B -A
Отобразить все активные процессы.

.TP
.B -x
Отобразить процессы, не привязанные к контролирующему терминалу
(демоны, работающие в фоновом режиме).

.SS ИЗМЕНЕНИЕ ВЫВОДА КОМАНДЫ

См. раздел
.B ВЫВОД
для более подробной информации.

.TP
.B -f
Включить в вывод полную (\fIfull\fP) информацию.

.TP
.B -l
Включить в вывод подробную (\fIlong\fP) информацию.
