.TH PS 1 "Весна 2019" "СПО, лабораторная работа №2"

.SH НАЗВАНИЕ
ps \- отображает состояние процессов на момент выполнения команды

.SH СИНТАКСИС
.B ps
[\fIопции\fP]

.SH ОПИСАНИЕ
.B ps
отображает информацию о выполняющихся процессах. По умолчанию выбираются
процессы c действующем идентификатором пользователя и терминалом, с которыми
вызван \fBps\fP, то есть \fBeffective uid = $EUID, tty = $TTY\fP. Вывод
состоит из ID процесса, идентификатора терминала, времени исполнения и названия команды.

.SH ПАРАМЕТРЫ

.TP
.B -a
Отобразить процессы всех пользователей.

.TP
.B -x
Включить в вывод процессы, не привязанные к контролирующему терминалу
(демоны, работающие в фоновом режиме).

